project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2

website:
  title: "EEFAbook"
  site-url: "https://EEFAbook.github.io/eefabook-notebook"
  description: "The EEFAbook content, ported to use the Earth Engine Python API."
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/EEFAbook/eefabook-notebook"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/EEFAbook/eefabook-notebook"
      - icon: twitter
        href: "https://twitter.com/eefabook"
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]